"""empty message

Revision ID: 393a684b74dc
Revises: 70600dcc1e72
Create Date: 2021-05-09 17:14:49.516533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393a684b74dc'
down_revision = '70600dcc1e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlists',
    sa.Column('book_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlists')
    # ### end Alembic commands ###
