"""empty message

Revision ID: 70600dcc1e72
Revises: 
Create Date: 2021-05-09 13:00:45.967498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70600dcc1e72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('isbn', sa.String(length=200), nullable=True),
    sa.Column('auth', sa.String(length=200), nullable=True),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_user')
    op.drop_table('book')
    # ### end Alembic commands ###
